name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Request reviewers
        uses: peter-evans/request-reviewers@v2
        with:
          reviewers: |
            gosurim
            thstkddnr20
            keroro7729
            BSY3510
